### PR TITLE
Special-case infinite result of multiply

### PR DESCRIPTION
**Pull request by dpsanders**
If result is infinite, return 0 as second component.

### CODE REVIEW

**Comment by dpsanders** [comment]
~Unfortunately, this leads to a sizeable performance regression, from 1.5ns to 4ns.~
The new version using `ifelse` no longer has this problem :+1:

**Comment by dpsanders** [comment]
An alternative solution is for FastRounding to treat the NaN as a 0, but that seems a bit dangerous.

**Comment by dpsanders** [comment]
With the change in https://github.com/JeffreySarnoff/FastRounding.jl/pull/8,
I believe this is no longer necessary?

**Comment by JeffreySarnoff** [comment]
that would be great -- I will try (how does one grab older commits?)

**Comment by dpsanders** [comment]
In this case, it's just a question of "revert"ing (undoing) the Pull Request. 
There's a button "Revert" a few boxes above this. Click that and it will generate a new Pull Request to undo this change, which you then merge.

**Pull request merged**
